name: Build and Publish RTP-Engine

on:
  push:
    branches:
      - kaya
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64]
        platform:
          - linux/amd64
          - linux/arm64
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: "noninteractive"

    container:
      image: debian:11
      
    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        apt-get update && \
        apt-get install -y --no-install-recommends \
        build-essential \
        dpkg-dev \
        debhelper \
        default-libmysqlclient-dev \
        gperf \
        libxtables-dev \
        libip6tc-dev \
        libip4tc-dev \
        libavcodec-dev \
        libavfilter-dev \
        libavformat-dev \
        libavutil-dev \
        libbencode-perl \
        libcrypt-openssl-rsa-perl \
        libcrypt-rijndael-perl \
        libhiredis-dev \
        libio-multiplex-perl \
        libio-socket-inet6-perl \
        libjson-glib-dev \
        libdigest-crc-perl \
        libdigest-hmac-perl \
        libnet-interface-perl \
        libssl-dev \
        libsystemd-dev \
        libxmlrpc-core-c3-dev \
        libcurl4-openssl-dev \
        libevent-dev \
        libpcap0.8-dev \
        unzip \
        nfs-common \
        dkms \
        libspandsp-dev \
        libmosquitto-dev \
        python3-websockets \
        cmake \
        wget \
        libbcg729-0 \
        libbcg729-dev \
        libiptc-dev \
        libjson-perl \
        libmnl-dev \
        libncurses-dev \
        libnftnl-dev \
        libopus-dev \
        libtest2-suite-perl \
        liburing-dev \
        libwebsockets-dev \
        pandoc \
        pkgconf \
        systemd \
        discount \
        libswresample-dev \
        libpcre2-dev \
        libglib2.0-dev \
        libsocket6-perl \
        zlib1g-dev \
        ca-certificates \
        curl

    - name: Build Debian Package
      run: |
        dpkg-checkbuilddeps && \
        dpkg-buildpackage --no-sign -a${{ matrix.arch }}

    - name: Upload to Nexus
      env:
        NEXUS_URL: 'https://nexus.nerd4ever.com.br/repository/debian-11-${{ matrix.arch }}/'
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      run: |
        for package in ../*.deb; do
          echo "Uploading $package to $NEXUS_URL"
          curl -v -u "${NEXUS_USERNAME}:${NEXUS_PASSWORD}" \
            -H "Content-Type: multipart/form-data" \
            --data-binary "@$package" \
            "${NEXUS_URL}"
        done
    